
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.2-dark green 3-green 4-voilet
#style: styles-2
#style: styles-3
#style: styles-4
style: styles-5
#style: styles-6


#Profile information
name: Sharmili P
tagline: Engineering Student
pic: IMG_20170715_150217.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: 1996sharmi@gmail.com
phone: 8220021757
website: m.facebook.com/sharmi.ram1 #do not add http://
linkedin: 
github: SharmiliPattabiraman
twitter: '@webjeda'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
